# Generated by Django 2.2.4 on 2024-06-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_magazine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
