# Generated by Django 2.2.4 on 2024-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20201105_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default='Default'),
            preserve_default=False,
        ),
    ]
