# Generated by Django 2.2.4 on 2024-05-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0004_auto_20240521_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
