# Generated by Django 2.2.4 on 2024-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Actor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='Category',
        ),
        migrations.AddField(
            model_name='actor',
            name='Category',
            field=models.ManyToManyField(related_name='actors', to='Movie_Actor_app.Movie'),
        ),
    ]
