# Generated by Django 2.2.4 on 2024-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Actor_app', '0003_auto_20240518_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='actors', to='Movie_Actor_app.Actor'),
        ),
    ]
