# Generated by Django 2.2.4 on 2024-05-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Actor_app', '0004_auto_20240518_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
