# Generated by Django 2.2.4 on 2024-05-18 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Actor_app', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='image_url',
            new_name='url_image',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='Movie_Actor_app.Actor'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='Movie_Actor_app.Category'),
            preserve_default=False,
        ),
    ]
